'use client'

import { useState, useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { motion } from 'framer-motion'
import {
  Users,
  Search,
  Plus,
  Edit3,
  Trash2,
  Eye,
  Shield,
  UserCheck,
  Filter,
  Download,
  MoreVertical,
  AlertCircle,
  CheckCircle,
  X,
  Save,
  Mail,
  Phone,
  Calendar,
  MapPin,
  User
} from 'lucide-react'
import { adminAPI, authAPI, apiUtils, type User as UserType } from '@/services/api'

interface AdminStats {
  totalUsers: number
  activeUsers: number
  inactiveUsers: number
  totalStudents: number
  totalAdmins: number
  recentRegistrations: number
}

interface UserFormData {
  email: string
  firstName: string
  lastName: string
  role: 'student' | 'admin'
  studentId?: string
  phone?: string
  status: 'active' | 'inactive'
}

export default function AdminDashboard() {
  const [users, setUsers] = useState<UserType[]>([])
  const [stats, setStats] = useState<AdminStats | null>(null)
  const [loading, setLoading] = useState(true)
  const [searchTerm, setSearchTerm] = useState('')
  const [roleFilter, setRoleFilter] = useState('')
  const [statusFilter, setStatusFilter] = useState('')
  const [showUserModal, setShowUserModal] = useState(false)
  const [editingUser, setEditingUser] = useState<UserType | null>(null)
  const [deleteConfirm, setDeleteConfirm] = useState<UserType | null>(null)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')

  const {
    register,
    handleSubmit,
    reset,
    setValue,
    formState: { errors },
  } = useForm<UserFormData>()

  useEffect(() => {
    checkAdminAccess()
    loadDashboardData()
  }, [])

  useEffect(() => {
    loadUsers()
  }, [searchTerm, roleFilter, statusFilter])

  const checkAdminAccess = async () => {
    try {
      const response = await authAPI.getCurrentUser()
      if (!response.success || !apiUtils.isAdmin(response.data?.user!)) {
        window.location.href = '/login'
      }
    } catch (err) {
      window.location.href = '/login'
    }
  }

  const loadDashboardData = async () => {
    try {
      const response = await adminAPI.getStats()
      if (response.success) {
        setStats(response.data?.stats || null)
      }
    } catch (err: any) {
      setError(apiUtils.handleError(err))
    }
  }

  const loadUsers = async () => {
    try {
      setLoading(true)
      const response = await adminAPI.getUsers({
        search: searchTerm,
        role: roleFilter,
        status: statusFilter,
        limit: 50,
      })

      if (response.success) {
        setUsers(response.data?.users || [])
      }
    } catch (err: any) {
      setError(apiUtils.handleError(err))
    } finally {
      setLoading(false)
    }
  }

  const handleCreateUser = () => {
    setEditingUser(null)
    reset({
      role: 'student',
      status: 'active',
    })
    setShowUserModal(true)
  }

  const handleEditUser = (user: UserType) => {
    setEditingUser(user)
    reset({
      email: user.email,
      firstName: user.firstName,
      lastName: user.lastName,
      role: user.role as 'student' | 'admin',
      studentId: user.studentId || '',
      phone: user.phone || '',
      status: user.status as 'active' | 'inactive',
    })
    setShowUserModal(true)
  }

  const handleDeleteUser = async (user: UserType) => {
    try {
      const response = await adminAPI.deleteUser(user.id)
      if (response.success) {
        setSuccess('User deactivated successfully')
        setDeleteConfirm(null)
        loadUsers()
        loadDashboardData()
        setTimeout(() => setSuccess(''), 3000)
      } else {
        setError(response.message || 'Failed to delete user')
      }
    } catch (err: any) {
      setError(apiUtils.handleError(err))
    }
  }

  const onSubmit = async (data: UserFormData) => {
    try {
      setError('')
      setSuccess('')

      if (editingUser) {
        // Update user
        const response = await adminAPI.updateUser(editingUser.id, data)
        if (response.success) {
          setSuccess('User updated successfully')
          setShowUserModal(false)
          loadUsers()
          loadDashboardData()
          setTimeout(() => setSuccess(''), 3000)
        } else {
          setError(response.message || 'Failed to update user')
        }
      } else {
        // Create user
        const response = await adminAPI.createUser({
          ...data,
          password: '', // Will be generated by backend
          generatePassword: true,
        } as any)
        if (response.success) {
          setSuccess(`User created successfully. Temporary password: ${response.data?.temporaryPassword}`)
          setShowUserModal(false)
          loadUsers()
          loadDashboardData()
        } else {
          setError(response.message || 'Failed to create user')
        }
      }
    } catch (err: any) {
      setError(apiUtils.handleError(err))
    }
  }

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    })
  }

  return (
    <div className="min-h-screen p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-8"
        >
          <h1 className="text-3xl font-bold text-white text-shadow mb-2 flex items-center justify-center">
            <Shield className="w-8 h-8 mr-3 text-purple-400" />
            Admin Dashboard
          </h1>
          <p className="text-white/80">
            Manage students and system administration
          </p>
        </motion.div>

        {/* Alerts */}
        {success && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="mb-6 bg-green-500/20 border border-green-500/30 rounded-xl p-4 flex items-center space-x-3"
          >
            <CheckCircle className="w-5 h-5 text-green-400 flex-shrink-0" />
            <p className="text-green-300 text-sm">{success}</p>
          </motion.div>
        )}

        {error && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="mb-6 bg-red-500/20 border border-red-500/30 rounded-xl p-4 flex items-center space-x-3"
          >
            <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0" />
            <p className="text-red-300 text-sm">{error}</p>
          </motion.div>
        )}

        {/* Stats Cards */}
        {stats && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4 mb-8"
          >
            <div className="glass-card text-center">
              <div className="text-3xl font-bold text-blue-400 mb-2">{stats.totalUsers}</div>
              <div className="text-white/80 text-sm">Total Users</div>
            </div>
            <div className="glass-card text-center">
              <div className="text-3xl font-bold text-green-400 mb-2">{stats.activeUsers}</div>
              <div className="text-white/80 text-sm">Active Users</div>
            </div>
            <div className="glass-card text-center">
              <div className="text-3xl font-bold text-red-400 mb-2">{stats.inactiveUsers}</div>
              <div className="text-white/80 text-sm">Inactive Users</div>
            </div>
            <div className="glass-card text-center">
              <div className="text-3xl font-bold text-blue-400 mb-2">{stats.totalStudents}</div>
              <div className="text-white/80 text-sm">Students</div>
            </div>
            <div className="glass-card text-center">
              <div className="text-3xl font-bold text-purple-400 mb-2">{stats.totalAdmins}</div>
              <div className="text-white/80 text-sm">Admins</div>
            </div>
            <div className="glass-card text-center">
              <div className="text-3xl font-bold text-yellow-400 mb-2">{stats.recentRegistrations}</div>
              <div className="text-white/80 text-sm">Recent (30d)</div>
            </div>
          </motion.div>
        )}

        {/* Users Management */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="glass-card"
        >
          {/* Header */}
          <div className="flex flex-col md:flex-row md:items-center md:justify-between mb-6">
            <h2 className="text-xl font-semibold text-white mb-4 md:mb-0 flex items-center">
              <Users className="w-6 h-6 mr-2" />
              User Management
            </h2>
            <button
              onClick={handleCreateUser}
              className="btn-primary flex items-center space-x-2"
            >
              <Plus className="w-4 h-4" />
              <span>Add User</span>
            </button>
          </div>

          {/* Filters */}
          <div className="flex flex-col md:flex-row gap-4 mb-6">
            <div className="flex-1">
              <div className="relative">
                <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-white/60" />
                <input
                  type="text"
                  placeholder="Search users..."
                  className="form-input pl-10"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                />
              </div>
            </div>
            <select
              className="form-input"
              value={roleFilter}
              onChange={(e) => setRoleFilter(e.target.value)}
            >
              <option value="">All Roles</option>
              <option value="student">Students</option>
              <option value="admin">Admins</option>
            </select>
            <select
              className="form-input"
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
            >
              <option value="">All Status</option>
              <option value="active">Active</option>
              <option value="inactive">Inactive</option>
            </select>
          </div>

          {/* Users Table */}
          <div className="overflow-x-auto">
            {loading ? (
              <div className="text-center py-8">
                <div className="spinner mx-auto"></div>
                <p className="text-white/70 mt-2">Loading users...</p>
              </div>
            ) : users.length === 0 ? (
              <div className="text-center py-8">
                <Users className="w-16 h-16 text-white/30 mx-auto mb-4" />
                <p className="text-white/70">No users found</p>
              </div>
            ) : (
              <table className="w-full">
                <thead>
                  <tr className="border-b border-white/10">
                    <th className="text-left text-white/80 font-medium py-3">User</th>
                    <th className="text-left text-white/80 font-medium py-3">Role</th>
                    <th className="text-left text-white/80 font-medium py-3">Status</th>
                    <th className="text-left text-white/80 font-medium py-3">Created</th>
                    <th className="text-left text-white/80 font-medium py-3">Last Login</th>
                    <th className="text-right text-white/80 font-medium py-3">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {users.map((user) => (
                    <tr key={user.id} className="border-b border-white/5 hover:bg-white/5 transition-colors">
                      <td className="py-4">
                        <div className="flex items-center space-x-3">
                          <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-400 to-purple-500 flex items-center justify-center">
                            {user.profilePicture ? (
                              <img 
                                src={user.profilePicture} 
                                alt="Profile" 
                                className="w-10 h-10 rounded-full object-cover"
                              />
                            ) : (
                              <User className="w-5 h-5 text-white" />
                            )}
                          </div>
                          <div>
                            <div className="text-white font-medium">
                              {apiUtils.formatUserName(user)}
                            </div>
                            <div className="text-white/60 text-sm">{user.email}</div>
                            {user.studentId && (
                              <div className="text-blue-400 text-xs">ID: {user.studentId}</div>
                            )}
                          </div>
                        </div>
                      </td>
                      <td className="py-4">
                        <span className={user.role === 'admin' ? 'role-admin' : 'role-student'}>
                          {user.role === 'admin' ? (
                            <>
                              <Shield className="w-3 h-3 inline mr-1" />
                              Admin
                            </>
                          ) : (
                            <>
                              <UserCheck className="w-3 h-3 inline mr-1" />
                              Student
                            </>
                          )}
                        </span>
                      </td>
                      <td className="py-4">
                        <span className={user.status === 'active' ? 'status-active' : 'status-inactive'}>
                          {user.status === 'active' ? 'Active' : 'Inactive'}
                        </span>
                      </td>
                      <td className="py-4 text-white/70 text-sm">
                        {formatDate(user.createdAt)}
                      </td>
                      <td className="py-4 text-white/70 text-sm">
                        {user.lastLogin ? formatDate(user.lastLogin) : 'Never'}
                      </td>
                      <td className="py-4 text-right">
                        <div className="flex items-center justify-end space-x-2">
                          <button
                            onClick={() => handleEditUser(user)}
                            className="p-2 text-white/60 hover:text-blue-400 transition-colors"
                            title="Edit User"
                          >
                            <Edit3 className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => setDeleteConfirm(user)}
                            className="p-2 text-white/60 hover:text-red-400 transition-colors"
                            title="Delete User"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </motion.div>

        {/* User Modal */}
        {showUserModal && (
          <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50">
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              className="glass-card w-full max-w-md"
            >
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-xl font-semibold text-white">
                  {editingUser ? 'Edit User' : 'Create User'}
                </h3>
                <button
                  onClick={() => setShowUserModal(false)}
                  className="text-white/60 hover:text-white transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
                {/* Email */}
                <div className="form-group">
                  <label className="form-label">
                    <Mail className="w-4 h-4 inline mr-2" />
                    Email
                  </label>
                  <input
                    type="email"
                    className={`form-input ${errors.email ? 'border-red-500/50' : ''}`}
                    disabled={!!editingUser}
                    {...register('email', {
                      required: 'Email is required',
                      pattern: {
                        value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                        message: 'Invalid email address',
                      },
                    })}
                  />
                  {errors.email && (
                    <span className="form-error">{errors.email.message}</span>
                  )}
                </div>

                {/* Name */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="form-group">
                    <label className="form-label">First Name</label>
                    <input
                      type="text"
                      className={`form-input ${errors.firstName ? 'border-red-500/50' : ''}`}
                      {...register('firstName', { required: 'First name is required' })}
                    />
                    {errors.firstName && (
                      <span className="form-error">{errors.firstName.message}</span>
                    )}
                  </div>
                  <div className="form-group">
                    <label className="form-label">Last Name</label>
                    <input
                      type="text"
                      className={`form-input ${errors.lastName ? 'border-red-500/50' : ''}`}
                      {...register('lastName', { required: 'Last name is required' })}
                    />
                    {errors.lastName && (
                      <span className="form-error">{errors.lastName.message}</span>
                    )}
                  </div>
                </div>

                {/* Role and Status */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="form-group">
                    <label className="form-label">Role</label>
                    <select
                      className={`form-input ${errors.role ? 'border-red-500/50' : ''}`}
                      {...register('role', { required: 'Role is required' })}
                    >
                      <option value="student">Student</option>
                      <option value="admin">Admin</option>
                    </select>
                  </div>
                  <div className="form-group">
                    <label className="form-label">Status</label>
                    <select
                      className={`form-input ${errors.status ? 'border-red-500/50' : ''}`}
                      {...register('status', { required: 'Status is required' })}
                    >
                      <option value="active">Active</option>
                      <option value="inactive">Inactive</option>
                    </select>
                  </div>
                </div>

                {/* Student ID and Phone */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="form-group">
                    <label className="form-label">Student ID</label>
                    <input
                      type="text"
                      className="form-input"
                      {...register('studentId')}
                    />
                  </div>
                  <div className="form-group">
                    <label className="form-label">Phone</label>
                    <input
                      type="tel"
                      className="form-input"
                      {...register('phone')}
                    />
                  </div>
                </div>

                <div className="flex justify-end space-x-3 pt-4 border-t border-white/10">
                  <button
                    type="button"
                    onClick={() => setShowUserModal(false)}
                    className="px-6 py-2 text-white/70 hover:text-white transition-colors"
                  >
                    Cancel
                  </button>
                  <button type="submit" className="btn-primary flex items-center space-x-2">
                    <Save className="w-4 h-4" />
                    <span>{editingUser ? 'Update' : 'Create'}</span>
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}

        {/* Delete Confirmation Modal */}
        {deleteConfirm && (
          <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50">
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              className="glass-card w-full max-w-sm text-center"
            >
              <div className="w-16 h-16 bg-red-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
                <AlertCircle className="w-8 h-8 text-red-400" />
              </div>
              <h3 className="text-lg font-semibold text-white mb-2">Confirm Deletion</h3>
              <p className="text-white/70 mb-6">
                Are you sure you want to deactivate{' '}
                <span className="font-medium text-white">
                  {apiUtils.formatUserName(deleteConfirm)}
                </span>
                ? This action can be reversed later.
              </p>
              <div className="flex justify-center space-x-3">
                <button
                  onClick={() => setDeleteConfirm(null)}
                  className="px-6 py-2 text-white/70 hover:text-white transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={() => handleDeleteUser(deleteConfirm)}
                  className="btn-danger flex items-center space-x-2"
                >
                  <Trash2 className="w-4 h-4" />
                  <span>Deactivate</span>
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </div>
    </div>
  )
}